/* ============================================================
   Vereins-Datenbank (Modus "Vereine")
   name · hint (Land · Liga) · c1/c2 Vereinsfarben · ab Kürzel (Wappen)
   ============================================================ */
window.CLUBS = [
  { name: "Manchester City", hint: "England · Premier League", c1: "#6CABDD", c2: "#ffffff", ab: "MCI" },
  { name: "Manchester United", hint: "England · Premier League", c1: "#DA291C", c2: "#ffffff", ab: "MUN" },
  { name: "FC Liverpool", hint: "England · Premier League", c1: "#C8102E", c2: "#ffffff", ab: "LFC" },
  { name: "FC Arsenal", hint: "England · Premier League", c1: "#EF0107", c2: "#ffffff", ab: "ARS" },
  { name: "FC Chelsea", hint: "England · Premier League", c1: "#034694", c2: "#ffffff", ab: "CHE" },
  { name: "Tottenham Hotspur", hint: "England · Premier League", c1: "#132257", c2: "#ffffff", ab: "TOT" },
  { name: "Newcastle United", hint: "England · Premier League", c1: "#241F20", c2: "#ffffff", ab: "NEW" },
  { name: "Aston Villa", hint: "England · Premier League", c1: "#670E36", c2: "#95BFE5", ab: "AVL" },
  { name: "West Ham United", hint: "England · Premier League", c1: "#7A263A", c2: "#1BB1E7", ab: "WHU" },
  { name: "FC Everton", hint: "England · Premier League", c1: "#003399", c2: "#ffffff", ab: "EVE" },
  { name: "Real Madrid", hint: "Spanien · LaLiga", c1: "#FFFFFF", c2: "#FEBE10", ab: "RMA" },
  { name: "FC Barcelona", hint: "Spanien · LaLiga", c1: "#004D98", c2: "#A50044", ab: "BAR" },
  { name: "Atlético Madrid", hint: "Spanien · LaLiga", c1: "#CB3524", c2: "#ffffff", ab: "ATM" },
  { name: "FC Sevilla", hint: "Spanien · LaLiga", c1: "#D80027", c2: "#ffffff", ab: "SEV" },
  { name: "FC Valencia", hint: "Spanien · LaLiga", c1: "#F18E00", c2: "#000000", ab: "VAL" },
  { name: "Real Betis", hint: "Spanien · LaLiga", c1: "#00954C", c2: "#ffffff", ab: "BET" },
  { name: "Athletic Bilbao", hint: "Spanien · LaLiga", c1: "#EE2523", c2: "#ffffff", ab: "ATH" },
  { name: "FC Villarreal", hint: "Spanien · LaLiga", c1: "#FFE667", c2: "#005187", ab: "VIL" },
  { name: "Real Sociedad", hint: "Spanien · LaLiga", c1: "#0067B1", c2: "#ffffff", ab: "RSO" },
  { name: "FC Bayern München", hint: "Deutschland · Bundesliga", c1: "#DC052D", c2: "#ffffff", ab: "FCB" },
  { name: "Borussia Dortmund", hint: "Deutschland · Bundesliga", c1: "#FDE100", c2: "#000000", ab: "BVB" },
  { name: "RB Leipzig", hint: "Deutschland · Bundesliga", c1: "#DD0741", c2: "#ffffff", ab: "RBL" },
  { name: "Bayer Leverkusen", hint: "Deutschland · Bundesliga", c1: "#E32219", c2: "#000000", ab: "B04" },
  { name: "Eintracht Frankfurt", hint: "Deutschland · Bundesliga", c1: "#E1000F", c2: "#000000", ab: "SGE" },
  { name: "VfB Stuttgart", hint: "Deutschland · Bundesliga", c1: "#E30613", c2: "#ffffff", ab: "VFB" },
  { name: "Borussia Mönchengladbach", hint: "Deutschland · Bundesliga", c1: "#00A94D", c2: "#000000", ab: "BMG" },
  { name: "VfL Wolfsburg", hint: "Deutschland · Bundesliga", c1: "#65B32E", c2: "#ffffff", ab: "WOB" },
  { name: "SC Freiburg", hint: "Deutschland · Bundesliga", c1: "#E2001A", c2: "#000000", ab: "SCF" },
  { name: "TSG Hoffenheim", hint: "Deutschland · Bundesliga", c1: "#1961B5", c2: "#ffffff", ab: "TSG" },
  { name: "Werder Bremen", hint: "Deutschland · Bundesliga", c1: "#009A3D", c2: "#ffffff", ab: "SVW" },
  { name: "1. FC Union Berlin", hint: "Deutschland · Bundesliga", c1: "#EB1923", c2: "#F5D000", ab: "FCU" },
  { name: "1. FC Köln", hint: "Deutschland · Bundesliga", c1: "#ED1C24", c2: "#ffffff", ab: "KOE" },
  { name: "Hamburger SV", hint: "Deutschland · Bundesliga", c1: "#12579F", c2: "#000000", ab: "HSV" },
  { name: "FC Augsburg", hint: "Deutschland · Bundesliga", c1: "#BA3733", c2: "#46714D", ab: "FCA" },
  { name: "1. FSV Mainz 05", hint: "Deutschland · Bundesliga", c1: "#ED1C24", c2: "#ffffff", ab: "M05" },
  { name: "FC Schalke 04", hint: "Deutschland · 2. Bundesliga", c1: "#004D9D", c2: "#ffffff", ab: "S04" },
  { name: "Juventus Turin", hint: "Italien · Serie A", c1: "#000000", c2: "#ffffff", ab: "JUV" },
  { name: "AC Mailand", hint: "Italien · Serie A", c1: "#FB090B", c2: "#000000", ab: "MIL" },
  { name: "Inter Mailand", hint: "Italien · Serie A", c1: "#010E80", c2: "#000000", ab: "INT" },
  { name: "AS Rom", hint: "Italien · Serie A", c1: "#8E1F2F", c2: "#F0BC42", ab: "ROM" },
  { name: "SSC Neapel", hint: "Italien · Serie A", c1: "#12A0D7", c2: "#ffffff", ab: "NAP" },
  { name: "Lazio Rom", hint: "Italien · Serie A", c1: "#87D8F7", c2: "#ffffff", ab: "LAZ" },
  { name: "Fiorentina", hint: "Italien · Serie A", c1: "#482E92", c2: "#ffffff", ab: "FIO" },
  { name: "Atalanta Bergamo", hint: "Italien · Serie A", c1: "#1E71B8", c2: "#000000", ab: "ATA" },
  { name: "Paris Saint-Germain", hint: "Frankreich · Ligue 1", c1: "#004170", c2: "#DA291C", ab: "PSG" },
  { name: "Olympique Marseille", hint: "Frankreich · Ligue 1", c1: "#2FAEE0", c2: "#ffffff", ab: "OM" },
  { name: "Olympique Lyon", hint: "Frankreich · Ligue 1", c1: "#E01E24", c2: "#143C8B", ab: "OL" },
  { name: "AS Monaco", hint: "Frankreich · Ligue 1", c1: "#E51B22", c2: "#ffffff", ab: "ASM" },
  { name: "OGC Nizza", hint: "Frankreich · Ligue 1", c1: "#C1121C", c2: "#000000", ab: "NIC" },
  { name: "OSC Lille", hint: "Frankreich · Ligue 1", c1: "#E01E13", c2: "#00347B", ab: "LIL" },
  { name: "Ajax Amsterdam", hint: "Niederlande · Eredivisie", c1: "#D2122E", c2: "#ffffff", ab: "AJA" },
  { name: "PSV Eindhoven", hint: "Niederlande · Eredivisie", c1: "#EE2E24", c2: "#ffffff", ab: "PSV" },
  { name: "Feyenoord Rotterdam", hint: "Niederlande · Eredivisie", c1: "#E30613", c2: "#ffffff", ab: "FEY" },
  { name: "Benfica Lissabon", hint: "Portugal · Primeira Liga", c1: "#E30613", c2: "#ffffff", ab: "SLB" },
  { name: "FC Porto", hint: "Portugal · Primeira Liga", c1: "#003DA5", c2: "#ffffff", ab: "POR" },
  { name: "Sporting Lissabon", hint: "Portugal · Primeira Liga", c1: "#008057", c2: "#ffffff", ab: "SCP" },
  { name: "Galatasaray", hint: "Türkei · Süper Lig", c1: "#E30A17", c2: "#FDB912", ab: "GS" },
  { name: "Fenerbahçe", hint: "Türkei · Süper Lig", c1: "#16264C", c2: "#FFED00", ab: "FB" },
  { name: "Beşiktaş", hint: "Türkei · Süper Lig", c1: "#000000", c2: "#ffffff", ab: "BJK" },
  { name: "Celtic Glasgow", hint: "Schottland · Premiership", c1: "#016A3A", c2: "#ffffff", ab: "CEL" },
  { name: "Glasgow Rangers", hint: "Schottland · Premiership", c1: "#1B458F", c2: "#ffffff", ab: "RAN" },
  { name: "FC Brügge", hint: "Belgien · Pro League", c1: "#0A00A0", c2: "#000000", ab: "CLU" },
  { name: "RSC Anderlecht", hint: "Belgien · Pro League", c1: "#4E2A84", c2: "#ffffff", ab: "AND" },
  { name: "Olympiakos Piräus", hint: "Griechenland · Super League", c1: "#E30613", c2: "#ffffff", ab: "OLY" },
  { name: "Al-Hilal", hint: "Saudi-Arabien · Saudi Pro League", c1: "#0033A0", c2: "#ffffff", ab: "HIL" },
  { name: "Al-Nassr", hint: "Saudi-Arabien · Saudi Pro League", c1: "#F9E300", c2: "#003B7E", ab: "NAS" },
  { name: "Al-Ittihad", hint: "Saudi-Arabien · Saudi Pro League", c1: "#000000", c2: "#F4D03F", ab: "ITT" },
  { name: "Inter Miami", hint: "USA · MLS", c1: "#F7B5CD", c2: "#231F20", ab: "MIA" },
  { name: "LA Galaxy", hint: "USA · MLS", c1: "#00245D", c2: "#FFD200", ab: "LAG" },
  { name: "Boca Juniors", hint: "Argentinien · Liga Profesional", c1: "#00286F", c2: "#FDB913", ab: "BOC" },
  { name: "River Plate", hint: "Argentinien · Liga Profesional", c1: "#E1002A", c2: "#ffffff", ab: "RIV" },
  { name: "Flamengo", hint: "Brasilien · Série A", c1: "#C52613", c2: "#000000", ab: "FLA" },
  { name: "Palmeiras", hint: "Brasilien · Série A", c1: "#006437", c2: "#ffffff", ab: "PAL" },
  { name: "Corinthians", hint: "Brasilien · Série A", c1: "#000000", c2: "#ffffff", ab: "COR" },
  { name: "Santos FC", hint: "Brasilien · Série A", c1: "#000000", c2: "#ffffff", ab: "SAN" },
  { name: "Brighton & Hove Albion", hint: "England · Premier League", c1: "#0057B8", c2: "#ffffff", ab: "BHA" },
  { name: "Crystal Palace", hint: "England · Premier League", c1: "#C4122E", c2: "#1B458F", ab: "CRY" },
  { name: "Nottingham Forest", hint: "England · Premier League", c1: "#DD0000", c2: "#ffffff", ab: "NFO" },
  { name: "Wolverhampton Wanderers", hint: "England · Premier League", c1: "#FDB913", c2: "#231F20", ab: "WOL" },
  { name: "FC Fulham", hint: "England · Premier League", c1: "#FFFFFF", c2: "#000000", ab: "FUL" },
  { name: "FC Brentford", hint: "England · Premier League", c1: "#E30613", c2: "#ffffff", ab: "BRE" },
  { name: "Leeds United", hint: "England · Premier League", c1: "#1D428A", c2: "#FFCD00", ab: "LEE" },
  { name: "Sunderland AFC", hint: "England · Premier League", c1: "#EB172B", c2: "#ffffff", ab: "SUN" },
  { name: "FC Burnley", hint: "England · Premier League", c1: "#6A003A", c2: "#53A5DD", ab: "BUR" },
  { name: "Girona FC", hint: "Spanien · LaLiga", c1: "#CD2534", c2: "#ffffff", ab: "GIR" },
  { name: "Celta Vigo", hint: "Spanien · LaLiga", c1: "#8AC3EE", c2: "#ffffff", ab: "CTA" },
  { name: "RCD Espanyol", hint: "Spanien · LaLiga", c1: "#007FC8", c2: "#ffffff", ab: "ESP" },
  { name: "Getafe CF", hint: "Spanien · LaLiga", c1: "#005999", c2: "#ffffff", ab: "GET" },
  { name: "Torino FC", hint: "Italien · Serie A", c1: "#881600", c2: "#ffffff", ab: "TOR" },
  { name: "FC Bologna", hint: "Italien · Serie A", c1: "#A21C24", c2: "#1A2F48", ab: "BOL" },
  { name: "Genoa CFC", hint: "Italien · Serie A", c1: "#B4292F", c2: "#002859", ab: "GEN" },
  { name: "Udinese Calcio", hint: "Italien · Serie A", c1: "#000000", c2: "#ffffff", ab: "UDI" },
  { name: "Como 1907", hint: "Italien · Serie A", c1: "#003D86", c2: "#ffffff", ab: "COM" },
  { name: "RC Lens", hint: "Frankreich · Ligue 1", c1: "#FFE500", c2: "#E20613", ab: "LEN" },
  { name: "Stade Rennes", hint: "Frankreich · Ligue 1", c1: "#E23138", c2: "#000000", ab: "REN" },
  { name: "RC Strasbourg", hint: "Frankreich · Ligue 1", c1: "#009FE3", c2: "#ffffff", ab: "STR" },
  { name: "AZ Alkmaar", hint: "Niederlande · Eredivisie", c1: "#E30613", c2: "#ffffff", ab: "AZ" },
  { name: "FC Twente", hint: "Niederlande · Eredivisie", c1: "#E1001A", c2: "#ffffff", ab: "TWE" },
  { name: "SC Braga", hint: "Portugal · Primeira Liga", c1: "#AA1B22", c2: "#ffffff", ab: "BRA" },
  { name: "Trabzonspor", hint: "Türkei · Süper Lig", c1: "#7B1E23", c2: "#4A9BD8", ab: "TS" },
  { name: "KRC Genk", hint: "Belgien · Pro League", c1: "#005CA9", c2: "#ffffff", ab: "GNK" },
  { name: "Standard Lüttich", hint: "Belgien · Pro League", c1: "#E30613", c2: "#ffffff", ab: "STL" },
  { name: "Panathinaikos Athen", hint: "Griechenland · Super League", c1: "#005F32", c2: "#ffffff", ab: "PAO" },
  { name: "AEK Athen", hint: "Griechenland · Super League", c1: "#FFDE00", c2: "#000000", ab: "AEK" },
  { name: "PAOK Thessaloniki", hint: "Griechenland · Super League", c1: "#000000", c2: "#ffffff", ab: "PAOK" },
  { name: "Red Bull Salzburg", hint: "Österreich · Bundesliga", c1: "#D0092A", c2: "#ffffff", ab: "RBS" },
  { name: "Rapid Wien", hint: "Österreich · Bundesliga", c1: "#006C3B", c2: "#ffffff", ab: "RAP" },
  { name: "FC Basel", hint: "Schweiz · Super League", c1: "#DA291C", c2: "#002D5A", ab: "BAS" },
  { name: "BSC Young Boys", hint: "Schweiz · Super League", c1: "#FFE500", c2: "#000000", ab: "YB" },
  { name: "Schachtar Donezk", hint: "Ukraine · Premier League", c1: "#F58220", c2: "#000000", ab: "SHA" },
  { name: "Dynamo Kiew", hint: "Ukraine · Premier League", c1: "#005BAB", c2: "#ffffff", ab: "DYN" },
  { name: "Dinamo Zagreb", hint: "Kroatien · HNL", c1: "#0067B2", c2: "#ffffff", ab: "DZG" },
  { name: "Roter Stern Belgrad", hint: "Serbien · SuperLiga", c1: "#E30613", c2: "#ffffff", ab: "RSB" },
  { name: "Sparta Prag", hint: "Tschechien · Fortuna Liga", c1: "#7A1729", c2: "#F2C500", ab: "SPP" },
  { name: "Slavia Prag", hint: "Tschechien · Fortuna Liga", c1: "#D0021B", c2: "#ffffff", ab: "SLA" },
  { name: "FK Bodø/Glimt", hint: "Norwegen · Eliteserien", c1: "#FFD100", c2: "#000000", ab: "BOD" },
  { name: "Al-Ahli", hint: "Saudi-Arabien · Saudi Pro League", c1: "#00844A", c2: "#ffffff", ab: "AHL" },
  { name: "Los Angeles FC", hint: "USA · MLS", c1: "#000000", c2: "#C39E6D", ab: "LAFC" },
  { name: "Seattle Sounders", hint: "USA · MLS", c1: "#5D9741", c2: "#005595", ab: "SEA" },
  { name: "Club América", hint: "Mexiko · Liga MX", c1: "#FFE600", c2: "#002D62", ab: "AME" },
  { name: "CD Guadalajara", hint: "Mexiko · Liga MX", c1: "#C8102E", c2: "#0033A0", ab: "GDL" },
  { name: "CF Monterrey", hint: "Mexiko · Liga MX", c1: "#001E62", c2: "#ffffff", ab: "MTY" },
  { name: "Tigres UANL", hint: "Mexiko · Liga MX", c1: "#FFB300", c2: "#00274C", ab: "TIG" },
  { name: "Racing Club", hint: "Argentinien · Liga Profesional", c1: "#6CB7E4", c2: "#ffffff", ab: "RAC" },
  { name: "Independiente", hint: "Argentinien · Liga Profesional", c1: "#E1000F", c2: "#ffffff", ab: "IND" },
  { name: "São Paulo FC", hint: "Brasilien · Série A", c1: "#FE0000", c2: "#000000", ab: "SPA" },
  { name: "Fluminense", hint: "Brasilien · Série A", c1: "#870A28", c2: "#0A5C36", ab: "FLU" },
  { name: "Botafogo", hint: "Brasilien · Série A", c1: "#000000", c2: "#ffffff", ab: "BOT" },
  { name: "Grêmio", hint: "Brasilien · Série A", c1: "#0D80BF", c2: "#000000", ab: "GRE" },
  { name: "SC Internacional", hint: "Brasilien · Série A", c1: "#E5050F", c2: "#ffffff", ab: "SCI" },
  { name: "Atlético Mineiro", hint: "Brasilien · Série A", c1: "#000000", c2: "#ffffff", ab: "CAM" },
  { name: "Cruzeiro", hint: "Brasilien · Série A", c1: "#003DA5", c2: "#ffffff", ab: "CRU" },
  { name: "Vasco da Gama", hint: "Brasilien · Série A", c1: "#000000", c2: "#ffffff", ab: "VAS" },
  { name: "Al Ahly", hint: "Ägypten · Premier League", c1: "#C8102E", c2: "#ffffff", ab: "AHLY" },
  { name: "Zamalek", hint: "Ägypten · Premier League", c1: "#D2122E", c2: "#ffffff", ab: "ZAM" },
].filter(function (c) { return c.name && c.hint; });
