/* ============================================================
   Vereins-Datenbank (Modus "Vereine")
   Nur bekannte Klubs. hint: kurzer Tipp (Land · Liga)
   ============================================================ */
window.CLUBS = [
  { name: "Manchester City", hint: "England · Premier League" },
  { name: "Manchester United", hint: "England · Premier League" },
  { name: "FC Liverpool", hint: "England · Premier League" },
  { name: "FC Arsenal", hint: "England · Premier League" },
  { name: "FC Chelsea", hint: "England · Premier League" },
  { name: "Tottenham Hotspur", hint: "England · Premier League" },
  { name: "Newcastle United", hint: "England · Premier League" },
  { name: "Aston Villa", hint: "England · Premier League" },
  { name: "West Ham United", hint: "England · Premier League" },
  { name: "FC Everton", hint: "England · Premier League" },
  { name: "Real Madrid", hint: "Spanien · LaLiga" },
  { name: "FC Barcelona", hint: "Spanien · LaLiga" },
  { name: "Atlético Madrid", hint: "Spanien · LaLiga" },
  { name: "FC Sevilla", hint: "Spanien · LaLiga" },
  { name: "FC Valencia", hint: "Spanien · LaLiga" },
  { name: "Real Betis", hint: "Spanien · LaLiga" },
  { name: "Athletic Bilbao", hint: "Spanien · LaLiga" },
  { name: "FC Villarreal", hint: "Spanien · LaLiga" },
  { name: "Real Sociedad", hint: "Spanien · LaLiga" },
  { name: "FC Bayern München", hint: "Deutschland · Bundesliga" },
  { name: "Borussia Dortmund", hint: "Deutschland · Bundesliga" },
  { name: "RB Leipzig", hint: "Deutschland · Bundesliga" },
  { name: "Bayer Leverkusen", hint: "Deutschland · Bundesliga" },
  { name: "Eintracht Frankfurt", hint: "Deutschland · Bundesliga" },
  { name: "VfB Stuttgart", hint: "Deutschland · Bundesliga" },
  { name: "Borussia Mönchengladbach", hint: "Deutschland · Bundesliga" },
  { name: "VfL Wolfsburg", hint: "Deutschland · Bundesliga" },
  { name: "SC Freiburg", hint: "Deutschland · Bundesliga" },
  { name: "TSG Hoffenheim", hint: "Deutschland · Bundesliga" },
  { name: "Werder Bremen", hint: "Deutschland · Bundesliga" },
  { name: "1. FC Union Berlin", hint: "Deutschland · Bundesliga" },
  { name: "1. FC Köln", hint: "Deutschland · Bundesliga" },
  { name: "Hamburger SV", hint: "Deutschland · Bundesliga" },
  { name: "FC Augsburg", hint: "Deutschland · Bundesliga" },
  { name: "1. FSV Mainz 05", hint: "Deutschland · Bundesliga" },
  { name: "FC Schalke 04", hint: "Deutschland · 2. Bundesliga" },
  { name: "Juventus Turin", hint: "Italien · Serie A" },
  { name: "AC Mailand", hint: "Italien · Serie A" },
  { name: "Inter Mailand", hint: "Italien · Serie A" },
  { name: "AS Rom", hint: "Italien · Serie A" },
  { name: "SSC Neapel", hint: "Italien · Serie A" },
  { name: "Lazio Rom", hint: "Italien · Serie A" },
  { name: "Fiorentina", hint: "Italien · Serie A" },
  { name: "Atalanta Bergamo", hint: "Italien · Serie A" },
  { name: "Paris Saint-Germain", hint: "Frankreich · Ligue 1" },
  { name: "Olympique Marseille", hint: "Frankreich · Ligue 1" },
  { name: "Olympique Lyon", hint: "Frankreich · Ligue 1" },
  { name: "AS Monaco", hint: "Frankreich · Ligue 1" },
  { name: "OGC Nizza", hint: "Frankreich · Ligue 1" },
  { name: "OSC Lille", hint: "Frankreich · Ligue 1" },
  { name: "Ajax Amsterdam", hint: "Niederlande · Eredivisie" },
  { name: "PSV Eindhoven", hint: "Niederlande · Eredivisie" },
  { name: "Feyenoord Rotterdam", hint: "Niederlande · Eredivisie" },
  { name: "Benfica Lissabon", hint: "Portugal · Primeira Liga" },
  { name: "FC Porto", hint: "Portugal · Primeira Liga" },
  { name: "Sporting Lissabon", hint: "Portugal · Primeira Liga" },
  { name: "Galatasaray", hint: "Türkei · Süper Lig" },
  { name: "Fenerbahçe", hint: "Türkei · Süper Lig" },
  { name: "Beşiktaş", hint: "Türkei · Süper Lig" },
  { name: "Celtic Glasgow", hint: "Schottland · Premiership" },
  { name: "Glasgow Rangers", hint: "Schottland · Premiership" },
  { name: "FC Brügge", hint: "Belgien · Pro League" },
  { name: "RSC Anderlecht", hint: "Belgien · Pro League" },
  { name: "Olympiakos Piräus", hint: "Griechenland · Super League" },
  { name: "Al-Hilal", hint: "Saudi-Arabien · Saudi Pro League" },
  { name: "Al-Nassr", hint: "Saudi-Arabien · Saudi Pro League" },
  { name: "Al-Ittihad", hint: "Saudi-Arabien · Saudi Pro League" },
  { name: "Inter Miami", hint: "USA · MLS" },
  { name: "LA Galaxy", hint: "USA · MLS" },
  { name: "Boca Juniors", hint: "Argentinien · Liga Profesional" },
  { name: "River Plate", hint: "Argentinien · Liga Profesional" },
  { name: "Flamengo", hint: "Brasilien · Série A" },
  { name: "Palmeiras", hint: "Brasilien · Série A" },
  { name: "Corinthians", hint: "Brasilien · Série A" },
  { name: "Santos FC", hint: "Brasilien · Série A" },
  { name: "Brighton & Hove Albion", hint: "England · Premier League" },
  { name: "Crystal Palace", hint: "England · Premier League" },
  { name: "Nottingham Forest", hint: "England · Premier League" },
  { name: "Wolverhampton Wanderers", hint: "England · Premier League" },
  { name: "FC Fulham", hint: "England · Premier League" },
  { name: "FC Brentford", hint: "England · Premier League" },
  { name: "Leeds United", hint: "England · Premier League" },
  { name: "Sunderland AFC", hint: "England · Premier League" },
  { name: "FC Burnley", hint: "England · Premier League" },
  { name: "Girona FC", hint: "Spanien · LaLiga" },
  { name: "Celta Vigo", hint: "Spanien · LaLiga" },
  { name: "RCD Espanyol", hint: "Spanien · LaLiga" },
  { name: "Getafe CF", hint: "Spanien · LaLiga" },
  { name: "Torino FC", hint: "Italien · Serie A" },
  { name: "FC Bologna", hint: "Italien · Serie A" },
  { name: "Genoa CFC", hint: "Italien · Serie A" },
  { name: "Udinese Calcio", hint: "Italien · Serie A" },
  { name: "Como 1907", hint: "Italien · Serie A" },
  { name: "RC Lens", hint: "Frankreich · Ligue 1" },
  { name: "Stade Rennes", hint: "Frankreich · Ligue 1" },
  { name: "RC Strasbourg", hint: "Frankreich · Ligue 1" },
  { name: "AZ Alkmaar", hint: "Niederlande · Eredivisie" },
  { name: "FC Twente", hint: "Niederlande · Eredivisie" },
  { name: "SC Braga", hint: "Portugal · Primeira Liga" },
  { name: "Trabzonspor", hint: "Türkei · Süper Lig" },
  { name: "KRC Genk", hint: "Belgien · Pro League" },
  { name: "Standard Lüttich", hint: "Belgien · Pro League" },
  { name: "Panathinaikos Athen", hint: "Griechenland · Super League" },
  { name: "AEK Athen", hint: "Griechenland · Super League" },
  { name: "PAOK Thessaloniki", hint: "Griechenland · Super League" },
  { name: "Red Bull Salzburg", hint: "Österreich · Bundesliga" },
  { name: "Rapid Wien", hint: "Österreich · Bundesliga" },
  { name: "FC Basel", hint: "Schweiz · Super League" },
  { name: "BSC Young Boys", hint: "Schweiz · Super League" },
  { name: "Schachtar Donezk", hint: "Ukraine · Premier League" },
  { name: "Dynamo Kiew", hint: "Ukraine · Premier League" },
  { name: "Dinamo Zagreb", hint: "Kroatien · HNL" },
  { name: "Roter Stern Belgrad", hint: "Serbien · SuperLiga" },
  { name: "Sparta Prag", hint: "Tschechien · Fortuna Liga" },
  { name: "Slavia Prag", hint: "Tschechien · Fortuna Liga" },
  { name: "FK Bodø/Glimt", hint: "Norwegen · Eliteserien" },
  { name: "Al-Ahli", hint: "Saudi-Arabien · Saudi Pro League" },
  { name: "Los Angeles FC", hint: "USA · MLS" },
  { name: "Seattle Sounders", hint: "USA · MLS" },
  { name: "Club América", hint: "Mexiko · Liga MX" },
  { name: "CD Guadalajara", hint: "Mexiko · Liga MX" },
  { name: "CF Monterrey", hint: "Mexiko · Liga MX" },
  { name: "Tigres UANL", hint: "Mexiko · Liga MX" },
  { name: "Racing Club", hint: "Argentinien · Liga Profesional" },
  { name: "Independiente", hint: "Argentinien · Liga Profesional" },
  { name: "São Paulo FC", hint: "Brasilien · Série A" },
  { name: "Fluminense", hint: "Brasilien · Série A" },
  { name: "Botafogo", hint: "Brasilien · Série A" },
  { name: "Grêmio", hint: "Brasilien · Série A" },
  { name: "SC Internacional", hint: "Brasilien · Série A" },
  { name: "Atlético Mineiro", hint: "Brasilien · Série A" },
  { name: "Cruzeiro", hint: "Brasilien · Série A" },
  { name: "Vasco da Gama", hint: "Brasilien · Série A" },
  { name: "Al Ahly", hint: "Ägypten · Premier League" },
  { name: "Zamalek", hint: "Ägypten · Premier League" },,

  // --- Weitere Vereine ---
  { name: "FC St. Pauli", hint: "Deutschland · Bundesliga" },
  { name: "1. FC Heidenheim", hint: "Deutschland · Bundesliga" },
  { name: "Hertha BSC", hint: "Deutschland · 2. Bundesliga" },
  { name: "Fortuna Düsseldorf", hint: "Deutschland · 2. Bundesliga" },
  { name: "1. FC Nürnberg", hint: "Deutschland · 2. Bundesliga" },
  { name: "Hannover 96", hint: "Deutschland · 2. Bundesliga" },
  { name: "Leicester City", hint: "England · Championship" },
  { name: "Southampton FC", hint: "England · Championship" },
  { name: "Norwich City", hint: "England · Championship" },
  { name: "Sheffield United", hint: "England · Championship" },
  { name: "Ipswich Town", hint: "England · Championship" },
  { name: "West Bromwich Albion", hint: "England · Championship" },
  { name: "Middlesbrough FC", hint: "England · Championship" },
  { name: "Rayo Vallecano", hint: "Spanien · LaLiga" },
  { name: "CA Osasuna", hint: "Spanien · LaLiga" },
  { name: "RCD Mallorca", hint: "Spanien · LaLiga" },
  { name: "Deportivo Alavés", hint: "Spanien · LaLiga" },
  { name: "Parma Calcio", hint: "Italien · Serie A" },
  { name: "Hellas Verona", hint: "Italien · Serie A" },
  { name: "US Sassuolo", hint: "Italien · Serie A" },
  { name: "Cagliari Calcio", hint: "Italien · Serie A" },
  { name: "AS Saint-Étienne", hint: "Frankreich · Ligue 1" },
  { name: "FC Nantes", hint: "Frankreich · Ligue 1" },
  { name: "Toulouse FC", hint: "Frankreich · Ligue 1" },
  { name: "Stade de Reims", hint: "Frankreich · Ligue 1" },
  { name: "Montpellier HSC", hint: "Frankreich · Ligue 1" },
  { name: "Stade Brest", hint: "Frankreich · Ligue 1" },
  { name: "FC Utrecht", hint: "Niederlande · Eredivisie" },
  { name: "Vitesse Arnheim", hint: "Niederlande · Eredivisie" },
  { name: "Vitória Guimarães", hint: "Portugal · Primeira Liga" },
  { name: "Boavista Porto", hint: "Portugal · Primeira Liga" },
  { name: "Royal Antwerpen", hint: "Belgien · Pro League" },
  { name: "KAA Gent", hint: "Belgien · Pro League" },
  { name: "Union Saint-Gilloise", hint: "Belgien · Pro League" },
  { name: "İstanbul Başakşehir", hint: "Türkei · Süper Lig" },
  { name: "Aberdeen FC", hint: "Schottland · Premiership" },
  { name: "Heart of Midlothian", hint: "Schottland · Premiership" },
  { name: "FC Zürich", hint: "Schweiz · Super League" },
  { name: "Grasshopper Club Zürich", hint: "Schweiz · Super League" },
  { name: "SK Sturm Graz", hint: "Österreich · Bundesliga" },
  { name: "FK Austria Wien", hint: "Österreich · Bundesliga" },
  { name: "Hajduk Split", hint: "Kroatien · HNL" },
  { name: "FK Partizan Belgrad", hint: "Serbien · SuperLiga" },
  { name: "Viktoria Pilsen", hint: "Tschechien · Fortuna Liga" },
  { name: "Legia Warschau", hint: "Polen · Ekstraklasa" },
  { name: "Lech Posen", hint: "Polen · Ekstraklasa" },
  { name: "FC Kopenhagen", hint: "Dänemark · Superliga" },
  { name: "Brøndby IF", hint: "Dänemark · Superliga" },
  { name: "FC Midtjylland", hint: "Dänemark · Superliga" },
  { name: "Malmö FF", hint: "Schweden · Allsvenskan" },
  { name: "AIK Solna", hint: "Schweden · Allsvenskan" },
  { name: "Hammarby IF", hint: "Schweden · Allsvenskan" },
  { name: "Rosenborg Trondheim", hint: "Norwegen · Eliteserien" },
  { name: "Molde FK", hint: "Norwegen · Eliteserien" },
  { name: "Atlanta United", hint: "USA · MLS" },
  { name: "New York Red Bulls", hint: "USA · MLS" },
  { name: "New York City FC", hint: "USA · MLS" },
  { name: "Columbus Crew", hint: "USA · MLS" },
  { name: "Portland Timbers", hint: "USA · MLS" },
  { name: "Cruz Azul", hint: "Mexiko · Liga MX" },
  { name: "Pumas UNAM", hint: "Mexiko · Liga MX" },
  { name: "Deportivo Toluca", hint: "Mexiko · Liga MX" },
  { name: "Athletico Paranaense", hint: "Brasilien · Série A" },
  { name: "EC Bahia", hint: "Brasilien · Série A" },
  { name: "Fortaleza EC", hint: "Brasilien · Série A" },
  { name: "RB Bragantino", hint: "Brasilien · Série A" },
  { name: "CA San Lorenzo", hint: "Argentinien · Liga Profesional" },
  { name: "Vélez Sarsfield", hint: "Argentinien · Liga Profesional" },
  { name: "Estudiantes de La Plata", hint: "Argentinien · Liga Profesional" },
  { name: "Peñarol Montevideo", hint: "Uruguay · Primera División" },
  { name: "Nacional Montevideo", hint: "Uruguay · Primera División" },
  { name: "Atlético Nacional", hint: "Kolumbien · Categoría Primera A" },
  { name: "Colo-Colo", hint: "Chile · Primera División" },
  { name: "Mamelodi Sundowns", hint: "Südafrika · Premier Division" },
  { name: "Kaizer Chiefs", hint: "Südafrika · Premier Division" },
  { name: "Orlando Pirates", hint: "Südafrika · Premier Division" },
  { name: "Wydad Casablanca", hint: "Marokko · Botola" },
  { name: "Raja Casablanca", hint: "Marokko · Botola" },
  { name: "Espérance Tunis", hint: "Tunesien · Ligue 1" },
  { name: "Urawa Red Diamonds", hint: "Japan · J1 League" },
  { name: "Kashima Antlers", hint: "Japan · J1 League" },
  { name: "Al-Shabab", hint: "Saudi-Arabien · Saudi Pro League" },
  { name: "Al-Ettifaq", hint: "Saudi-Arabien · Saudi Pro League" },
  { name: "Al-Sadd", hint: "Katar · Stars League" }
].filter(function (c) { return c.name && c.hint; });
