/* ============================================================
   Fußballer-Datenbank
   Nur bekannte Namen – aktive Spieler und Legenden/Ex-Profis.
   hint: kurzer Tipp für den Imposter (Position · Land)
   ============================================================ */
window.FOOTBALLERS = [
  // --- Superstars / Legenden ---
  { name: "Lionel Messi",           hint: "Stürmer · Argentinien" },
  { name: "Cristiano Ronaldo",      hint: "Stürmer · Portugal" },
  { name: "Neymar",                 hint: "Stürmer · Brasilien" },
  { name: "Kylian Mbappé",          hint: "Stürmer · Frankreich" },
  { name: "Erling Haaland",         hint: "Stürmer · Norwegen" },
  { name: "Kevin De Bruyne",        hint: "Mittelfeld · Belgien" },
  { name: "Mohamed Salah",          hint: "Flügel · Ägypten" },
  { name: "Robert Lewandowski",     hint: "Stürmer · Polen" },
  { name: "Luka Modrić",            hint: "Mittelfeld · Kroatien" },
  { name: "Toni Kroos",             hint: "Mittelfeld · Deutschland" },
  { name: "Zlatan Ibrahimović",     hint: "Stürmer · Schweden" },
  { name: "Karim Benzema",          hint: "Stürmer · Frankreich" },
  { name: "Luis Suárez",            hint: "Stürmer · Uruguay" },
  { name: "Antoine Griezmann",      hint: "Stürmer · Frankreich" },
  { name: "Harry Kane",             hint: "Stürmer · England" },
  { name: "Son Heung-min",          hint: "Flügel · Südkorea" },
  { name: "Gareth Bale",            hint: "Flügel · Wales" },

  // --- Neue Generation ---
  { name: "Jude Bellingham",        hint: "Mittelfeld · England" },
  { name: "Vinícius Júnior",        hint: "Flügel · Brasilien" },
  { name: "Pedri",                  hint: "Mittelfeld · Spanien" },
  { name: "Gavi",                   hint: "Mittelfeld · Spanien" },
  { name: "Jamal Musiala",          hint: "Mittelfeld · Deutschland" },
  { name: "Florian Wirtz",          hint: "Mittelfeld · Deutschland" },
  { name: "Bukayo Saka",            hint: "Flügel · England" },
  { name: "Phil Foden",             hint: "Mittelfeld · England" },
  { name: "Lautaro Martínez",       hint: "Stürmer · Argentinien" },
  { name: "Victor Osimhen",         hint: "Stürmer · Nigeria" },
  { name: "Rafael Leão",            hint: "Flügel · Portugal" },
  { name: "Federico Valverde",      hint: "Mittelfeld · Uruguay" },
  { name: "Rodri",                  hint: "Mittelfeld · Spanien" },
  { name: "Martin Ødegaard",        hint: "Mittelfeld · Norwegen" },
  { name: "Alexander Isak",         hint: "Stürmer · Schweden" },
  { name: "Khvicha Kvaratskhelia",  hint: "Flügel · Georgien" },
  { name: "Achraf Hakimi",          hint: "Verteidiger · Marokko" },

  // --- Aktuelle Stars ---
  { name: "Virgil van Dijk",        hint: "Verteidiger · Niederlande" },
  { name: "Trent Alexander-Arnold", hint: "Verteidiger · England" },
  { name: "Bruno Fernandes",        hint: "Mittelfeld · Portugal" },
  { name: "Bernardo Silva",         hint: "Mittelfeld · Portugal" },
  { name: "Rúben Dias",             hint: "Verteidiger · Portugal" },
  { name: "Marcus Rashford",        hint: "Stürmer · England" },
  { name: "Declan Rice",            hint: "Mittelfeld · England" },
  { name: "Jack Grealish",          hint: "Flügel · England" },
  { name: "N'Golo Kanté",           hint: "Mittelfeld · Frankreich" },
  { name: "Ousmane Dembélé",        hint: "Flügel · Frankreich" },
  { name: "Frenkie de Jong",        hint: "Mittelfeld · Niederlande" },
  { name: "Matthijs de Ligt",       hint: "Verteidiger · Niederlande" },
  { name: "Sadio Mané",             hint: "Flügel · Senegal" },
  { name: "Riyad Mahrez",           hint: "Flügel · Algerien" },
  { name: "Romelu Lukaku",          hint: "Stürmer · Belgien" },
  { name: "Federico Chiesa",        hint: "Flügel · Italien" },
  { name: "Christian Pulisic",      hint: "Flügel · USA" },
  { name: "Dušan Vlahović",         hint: "Stürmer · Serbien" },
  { name: "Cody Gakpo",             hint: "Flügel · Niederlande" },

  // --- Deutschland ---
  { name: "Manuel Neuer",           hint: "Torwart · Deutschland" },
  { name: "Joshua Kimmich",         hint: "Mittelfeld · Deutschland" },
  { name: "Thomas Müller",          hint: "Stürmer · Deutschland" },
  { name: "İlkay Gündoğan",         hint: "Mittelfeld · Deutschland" },
  { name: "Kai Havertz",            hint: "Stürmer · Deutschland" },
  { name: "Antonio Rüdiger",        hint: "Verteidiger · Deutschland" },
  { name: "Leroy Sané",             hint: "Flügel · Deutschland" },
  { name: "Serge Gnabry",           hint: "Flügel · Deutschland" },
  { name: "Marco Reus",             hint: "Flügel · Deutschland" },
  { name: "Mats Hummels",           hint: "Verteidiger · Deutschland" },
  { name: "Mesut Özil",             hint: "Mittelfeld · Deutschland" },
  { name: "Miroslav Klose",         hint: "Stürmer · Deutschland" },
  { name: "Philipp Lahm",           hint: "Verteidiger · Deutschland" },
  { name: "Bastian Schweinsteiger", hint: "Mittelfeld · Deutschland" },
  { name: "Oliver Kahn",            hint: "Torwart · Deutschland" },
  { name: "Michael Ballack",        hint: "Mittelfeld · Deutschland" },

  // --- Legenden / Ex-Profis ---
  { name: "Ronaldinho",             hint: "Mittelfeld · Brasilien" },
  { name: "Ronaldo Nazário",        hint: "Stürmer · Brasilien" },
  { name: "Kaká",                   hint: "Mittelfeld · Brasilien" },
  { name: "Roberto Carlos",         hint: "Verteidiger · Brasilien" },
  { name: "Cafu",                   hint: "Verteidiger · Brasilien" },
  { name: "Rivaldo",                hint: "Mittelfeld · Brasilien" },
  { name: "Zinedine Zidane",        hint: "Mittelfeld · Frankreich" },
  { name: "Thierry Henry",          hint: "Stürmer · Frankreich" },
  { name: "David Beckham",          hint: "Mittelfeld · England" },
  { name: "Wayne Rooney",           hint: "Stürmer · England" },
  { name: "Steven Gerrard",         hint: "Mittelfeld · England" },
  { name: "Frank Lampard",          hint: "Mittelfeld · England" },
  { name: "Andrés Iniesta",         hint: "Mittelfeld · Spanien" },
  { name: "Xavi",                   hint: "Mittelfeld · Spanien" },
  { name: "Carles Puyol",           hint: "Verteidiger · Spanien" },
  { name: "Iker Casillas",          hint: "Torwart · Spanien" },
  { name: "Sergio Ramos",           hint: "Verteidiger · Spanien" },
  { name: "Gerard Piqué",           hint: "Verteidiger · Spanien" },
  { name: "David Villa",            hint: "Stürmer · Spanien" },
  { name: "Fernando Torres",        hint: "Stürmer · Spanien" },
  { name: "Raúl",                   hint: "Stürmer · Spanien" },
  { name: "Andrea Pirlo",           hint: "Mittelfeld · Italien" },
  { name: "Gianluigi Buffon",       hint: "Torwart · Italien" },
  { name: "Francesco Totti",        hint: "Stürmer · Italien" },
  { name: "Alessandro Del Piero",   hint: "Stürmer · Italien" },
  { name: "Paolo Maldini",          hint: "Verteidiger · Italien" },
  { name: "Didier Drogba",          hint: "Stürmer · Elfenbeinküste" },
  { name: "Samuel Eto'o",           hint: "Stürmer · Kamerun" },
  { name: "Yaya Touré",             hint: "Mittelfeld · Elfenbeinküste" },
  { name: "Eden Hazard",            hint: "Flügel · Belgien" },
  { name: "Sergio Agüero",          hint: "Stürmer · Argentinien" },
  { name: "Ángel Di María",         hint: "Flügel · Argentinien" },
  { name: "Diego Maradona",         hint: "Mittelfeld · Argentinien" },
  { name: "Pelé",                   hint: "Stürmer · Brasilien" },
  { name: "Arjen Robben",           hint: "Flügel · Niederlande" },
  { name: "Robin van Persie",       hint: "Stürmer · Niederlande" },
  { name: "Wesley Sneijder",        hint: "Mittelfeld · Niederlande" },
  { name: "Dennis Bergkamp",        hint: "Stürmer · Niederlande" },
  { name: "Ruud van Nistelrooy",    hint: "Stürmer · Niederlande" },
  { name: "Andriy Shevchenko",      hint: "Stürmer · Ukraine" },
  { name: "Luís Figo",              hint: "Flügel · Portugal" },
  { name: "Petr Čech",              hint: "Torwart · Tschechien" },

  // --- Weitere aktuelle Torhüter / Verteidiger ---
  { name: "Alisson",                hint: "Torwart · Brasilien" },
  { name: "Ederson",                hint: "Torwart · Brasilien" },
  { name: "Thibaut Courtois",       hint: "Torwart · Belgien" },
  { name: "Gianluigi Donnarumma",   hint: "Torwart · Italien" },
  { name: "Marc-André ter Stegen",  hint: "Torwart · Deutschland" },
  { name: "Marcelo",                hint: "Verteidiger · Brasilien" },
  { name: "Dani Alves",             hint: "Verteidiger · Brasilien" },
  { name: "Thiago Silva",           hint: "Verteidiger · Brasilien" },
  { name: "Casemiro",               hint: "Mittelfeld · Brasilien" },
  { name: "Paul Pogba",             hint: "Mittelfeld · Frankreich" },
  { name: "Aurélien Tchouaméni",    hint: "Mittelfeld · Frankreich" },
  { name: "James Rodríguez",        hint: "Mittelfeld · Kolumbien" },
  { name: "Radamel Falcao",         hint: "Stürmer · Kolumbien" },
  { name: "Memphis Depay",          hint: "Stürmer · Niederlande" },
  { name: "Cesc Fàbregas",          hint: "Mittelfeld · Spanien" },
  { name: "David Silva",            hint: "Mittelfeld · Spanien" }
].filter(function (p) { return p.name && p.hint; });
