/* ============================================================
   Fußballer-Datenbank
   Nur bekannte Namen – aktive Spieler und Legenden/Ex-Profis.
   hint: kurzer Tipp für den Imposter (Position · Land)
   ============================================================ */
window.FOOTBALLERS = [
  // --- Superstars / Legenden ---
  { name: "Lionel Messi",           hint: "Stürmer · Argentinien" },
  { name: "Cristiano Ronaldo",      hint: "Stürmer · Portugal" },
  { name: "Neymar",                 hint: "Stürmer · Brasilien" },
  { name: "Kylian Mbappé",          hint: "Stürmer · Frankreich" },
  { name: "Erling Haaland",         hint: "Stürmer · Norwegen" },
  { name: "Kevin De Bruyne",        hint: "Mittelfeld · Belgien" },
  { name: "Mohamed Salah",          hint: "Flügel · Ägypten" },
  { name: "Robert Lewandowski",     hint: "Stürmer · Polen" },
  { name: "Luka Modrić",            hint: "Mittelfeld · Kroatien" },
  { name: "Toni Kroos",             hint: "Mittelfeld · Deutschland" },
  { name: "Zlatan Ibrahimović",     hint: "Stürmer · Schweden" },
  { name: "Karim Benzema",          hint: "Stürmer · Frankreich" },
  { name: "Luis Suárez",            hint: "Stürmer · Uruguay" },
  { name: "Antoine Griezmann",      hint: "Stürmer · Frankreich" },
  { name: "Harry Kane",             hint: "Stürmer · England" },
  { name: "Son Heung-min",          hint: "Flügel · Südkorea" },
  { name: "Gareth Bale",            hint: "Flügel · Wales" },

  // --- Neue Generation ---
  { name: "Jude Bellingham",        hint: "Mittelfeld · England" },
  { name: "Vinícius Júnior",        hint: "Flügel · Brasilien" },
  { name: "Pedri",                  hint: "Mittelfeld · Spanien" },
  { name: "Gavi",                   hint: "Mittelfeld · Spanien" },
  { name: "Jamal Musiala",          hint: "Mittelfeld · Deutschland" },
  { name: "Florian Wirtz",          hint: "Mittelfeld · Deutschland" },
  { name: "Bukayo Saka",            hint: "Flügel · England" },
  { name: "Phil Foden",             hint: "Mittelfeld · England" },
  { name: "Lautaro Martínez",       hint: "Stürmer · Argentinien" },
  { name: "Victor Osimhen",         hint: "Stürmer · Nigeria" },
  { name: "Rafael Leão",            hint: "Flügel · Portugal" },
  { name: "Federico Valverde",      hint: "Mittelfeld · Uruguay" },
  { name: "Rodri",                  hint: "Mittelfeld · Spanien" },
  { name: "Martin Ødegaard",        hint: "Mittelfeld · Norwegen" },
  { name: "Alexander Isak",         hint: "Stürmer · Schweden" },
  { name: "Khvicha Kvaratskhelia",  hint: "Flügel · Georgien" },
  { name: "Achraf Hakimi",          hint: "Verteidiger · Marokko" },

  // --- Aktuelle Stars ---
  { name: "Virgil van Dijk",        hint: "Verteidiger · Niederlande" },
  { name: "Trent Alexander-Arnold", hint: "Verteidiger · England" },
  { name: "Bruno Fernandes",        hint: "Mittelfeld · Portugal" },
  { name: "Bernardo Silva",         hint: "Mittelfeld · Portugal" },
  { name: "Rúben Dias",             hint: "Verteidiger · Portugal" },
  { name: "Marcus Rashford",        hint: "Stürmer · England" },
  { name: "Declan Rice",            hint: "Mittelfeld · England" },
  { name: "Jack Grealish",          hint: "Flügel · England" },
  { name: "N'Golo Kanté",           hint: "Mittelfeld · Frankreich" },
  { name: "Ousmane Dembélé",        hint: "Flügel · Frankreich" },
  { name: "Frenkie de Jong",        hint: "Mittelfeld · Niederlande" },
  { name: "Matthijs de Ligt",       hint: "Verteidiger · Niederlande" },
  { name: "Sadio Mané",             hint: "Flügel · Senegal" },
  { name: "Riyad Mahrez",           hint: "Flügel · Algerien" },
  { name: "Romelu Lukaku",          hint: "Stürmer · Belgien" },
  { name: "Federico Chiesa",        hint: "Flügel · Italien" },
  { name: "Christian Pulisic",      hint: "Flügel · USA" },
  { name: "Dušan Vlahović",         hint: "Stürmer · Serbien" },
  { name: "Cody Gakpo",             hint: "Flügel · Niederlande" },

  // --- Deutschland ---
  { name: "Manuel Neuer",           hint: "Torwart · Deutschland" },
  { name: "Joshua Kimmich",         hint: "Mittelfeld · Deutschland" },
  { name: "Thomas Müller",          hint: "Stürmer · Deutschland" },
  { name: "İlkay Gündoğan",         hint: "Mittelfeld · Deutschland" },
  { name: "Kai Havertz",            hint: "Stürmer · Deutschland" },
  { name: "Antonio Rüdiger",        hint: "Verteidiger · Deutschland" },
  { name: "Leroy Sané",             hint: "Flügel · Deutschland" },
  { name: "Serge Gnabry",           hint: "Flügel · Deutschland" },
  { name: "Marco Reus",             hint: "Flügel · Deutschland" },
  { name: "Mats Hummels",           hint: "Verteidiger · Deutschland" },
  { name: "Mesut Özil",             hint: "Mittelfeld · Deutschland" },
  { name: "Miroslav Klose",         hint: "Stürmer · Deutschland" },
  { name: "Philipp Lahm",           hint: "Verteidiger · Deutschland" },
  { name: "Bastian Schweinsteiger", hint: "Mittelfeld · Deutschland" },
  { name: "Oliver Kahn",            hint: "Torwart · Deutschland" },
  { name: "Michael Ballack",        hint: "Mittelfeld · Deutschland" },

  // --- Legenden / Ex-Profis ---
  { name: "Ronaldinho",             hint: "Mittelfeld · Brasilien" },
  { name: "Ronaldo Nazário",        hint: "Stürmer · Brasilien" },
  { name: "Kaká",                   hint: "Mittelfeld · Brasilien" },
  { name: "Roberto Carlos",         hint: "Verteidiger · Brasilien" },
  { name: "Cafu",                   hint: "Verteidiger · Brasilien" },
  { name: "Rivaldo",                hint: "Mittelfeld · Brasilien" },
  { name: "Zinedine Zidane",        hint: "Mittelfeld · Frankreich" },
  { name: "Thierry Henry",          hint: "Stürmer · Frankreich" },
  { name: "David Beckham",          hint: "Mittelfeld · England" },
  { name: "Wayne Rooney",           hint: "Stürmer · England" },
  { name: "Steven Gerrard",         hint: "Mittelfeld · England" },
  { name: "Frank Lampard",          hint: "Mittelfeld · England" },
  { name: "Andrés Iniesta",         hint: "Mittelfeld · Spanien" },
  { name: "Xavi",                   hint: "Mittelfeld · Spanien" },
  { name: "Carles Puyol",           hint: "Verteidiger · Spanien" },
  { name: "Iker Casillas",          hint: "Torwart · Spanien" },
  { name: "Sergio Ramos",           hint: "Verteidiger · Spanien" },
  { name: "Gerard Piqué",           hint: "Verteidiger · Spanien" },
  { name: "David Villa",            hint: "Stürmer · Spanien" },
  { name: "Fernando Torres",        hint: "Stürmer · Spanien" },
  { name: "Raúl",                   hint: "Stürmer · Spanien" },
  { name: "Andrea Pirlo",           hint: "Mittelfeld · Italien" },
  { name: "Gianluigi Buffon",       hint: "Torwart · Italien" },
  { name: "Francesco Totti",        hint: "Stürmer · Italien" },
  { name: "Alessandro Del Piero",   hint: "Stürmer · Italien" },
  { name: "Paolo Maldini",          hint: "Verteidiger · Italien" },
  { name: "Didier Drogba",          hint: "Stürmer · Elfenbeinküste" },
  { name: "Samuel Eto'o",           hint: "Stürmer · Kamerun" },
  { name: "Yaya Touré",             hint: "Mittelfeld · Elfenbeinküste" },
  { name: "Eden Hazard",            hint: "Flügel · Belgien" },
  { name: "Sergio Agüero",          hint: "Stürmer · Argentinien" },
  { name: "Ángel Di María",         hint: "Flügel · Argentinien" },
  { name: "Diego Maradona",         hint: "Mittelfeld · Argentinien" },
  { name: "Pelé",                   hint: "Stürmer · Brasilien" },
  { name: "Arjen Robben",           hint: "Flügel · Niederlande" },
  { name: "Robin van Persie",       hint: "Stürmer · Niederlande" },
  { name: "Wesley Sneijder",        hint: "Mittelfeld · Niederlande" },
  { name: "Dennis Bergkamp",        hint: "Stürmer · Niederlande" },
  { name: "Ruud van Nistelrooy",    hint: "Stürmer · Niederlande" },
  { name: "Andriy Shevchenko",      hint: "Stürmer · Ukraine" },
  { name: "Luís Figo",              hint: "Flügel · Portugal" },
  { name: "Petr Čech",              hint: "Torwart · Tschechien" },

  // --- Weitere aktuelle Torhüter / Verteidiger ---
  { name: "Alisson",                hint: "Torwart · Brasilien" },
  { name: "Ederson",                hint: "Torwart · Brasilien" },
  { name: "Thibaut Courtois",       hint: "Torwart · Belgien" },
  { name: "Gianluigi Donnarumma",   hint: "Torwart · Italien" },
  { name: "Marc-André ter Stegen",  hint: "Torwart · Deutschland" },
  { name: "Marcelo",                hint: "Verteidiger · Brasilien" },
  { name: "Dani Alves",             hint: "Verteidiger · Brasilien" },
  { name: "Thiago Silva",           hint: "Verteidiger · Brasilien" },
  { name: "Casemiro",               hint: "Mittelfeld · Brasilien" },
  { name: "Paul Pogba",             hint: "Mittelfeld · Frankreich" },
  { name: "Aurélien Tchouaméni",    hint: "Mittelfeld · Frankreich" },
  { name: "James Rodríguez",        hint: "Mittelfeld · Kolumbien" },
  { name: "Radamel Falcao",         hint: "Stürmer · Kolumbien" },
  { name: "Memphis Depay",          hint: "Stürmer · Niederlande" },
  { name: "Cesc Fàbregas",          hint: "Mittelfeld · Spanien" },
  { name: "David Silva",            hint: "Mittelfeld · Spanien" },

  // --- Aktuelle Spieler (Ergänzung) ---
  { name: "Emiliano Martínez", hint: "Torwart · Argentinien" },
  { name: "Mike Maignan", hint: "Torwart · Frankreich" },
  { name: "David Raya", hint: "Torwart · Spanien" },
  { name: "Jordan Pickford", hint: "Torwart · England" },
  { name: "Diogo Costa", hint: "Torwart · Portugal" },
  { name: "Yassine Bounou", hint: "Torwart · Marokko" },
  { name: "William Saliba", hint: "Verteidiger · Frankreich" },
  { name: "Jules Koundé", hint: "Verteidiger · Frankreich" },
  { name: "Theo Hernández", hint: "Verteidiger · Frankreich" },
  { name: "Dayot Upamecano", hint: "Verteidiger · Frankreich" },
  { name: "Benjamin Pavard", hint: "Verteidiger · Frankreich" },
  { name: "Dani Carvajal", hint: "Verteidiger · Spanien" },
  { name: "Éder Militão", hint: "Verteidiger · Brasilien" },
  { name: "Marquinhos", hint: "Verteidiger · Brasilien" },
  { name: "Gabriel Magalhães", hint: "Verteidiger · Brasilien" },
  { name: "David Alaba", hint: "Verteidiger · Österreich" },
  { name: "Kim Min-jae", hint: "Verteidiger · Südkorea" },
  { name: "Manuel Akanji", hint: "Verteidiger · Schweiz" },
  { name: "Kyle Walker", hint: "Verteidiger · England" },
  { name: "John Stones", hint: "Verteidiger · England" },
  { name: "Reece James", hint: "Verteidiger · England" },
  { name: "Joško Gvardiol", hint: "Verteidiger · Kroatien" },
  { name: "Cristian Romero", hint: "Verteidiger · Argentinien" },
  { name: "Lisandro Martínez", hint: "Verteidiger · Argentinien" },
  { name: "Alessandro Bastoni", hint: "Verteidiger · Italien" },
  { name: "Nuno Mendes", hint: "Verteidiger · Portugal" },
  { name: "João Cancelo", hint: "Verteidiger · Portugal" },
  { name: "Alphonso Davies", hint: "Verteidiger · Kanada" },
  { name: "Denzel Dumfries", hint: "Verteidiger · Niederlande" },
  { name: "Jurriën Timber", hint: "Verteidiger · Niederlande" },
  { name: "Jonathan Tah", hint: "Verteidiger · Deutschland" },
  { name: "David Raum", hint: "Verteidiger · Deutschland" },
  { name: "Dani Olmo", hint: "Mittelfeld · Spanien" },
  { name: "Enzo Fernández", hint: "Mittelfeld · Argentinien" },
  { name: "Alexis Mac Allister", hint: "Mittelfeld · Argentinien" },
  { name: "Dominik Szoboszlai", hint: "Mittelfeld · Ungarn" },
  { name: "Ryan Gravenberch", hint: "Mittelfeld · Niederlande" },
  { name: "Bruno Guimarães", hint: "Mittelfeld · Brasilien" },
  { name: "Gabriel Sara", hint: "Mittelfeld · Brasilien" },
  { name: "Sandro Tonali", hint: "Mittelfeld · Italien" },
  { name: "Nicolò Barella", hint: "Mittelfeld · Italien" },
  { name: "Hakan Çalhanoğlu", hint: "Mittelfeld · Türkei" },
  { name: "Vitinha", hint: "Mittelfeld · Portugal" },
  { name: "João Neves", hint: "Mittelfeld · Portugal" },
  { name: "Rúben Neves", hint: "Mittelfeld · Portugal" },
  { name: "Eduardo Camavinga", hint: "Mittelfeld · Frankreich" },
  { name: "Mateo Kovačić", hint: "Mittelfeld · Kroatien" },
  { name: "Granit Xhaka", hint: "Mittelfeld · Schweiz" },
  { name: "Scott McTominay", hint: "Mittelfeld · Schottland" },
  { name: "Christian Eriksen", hint: "Mittelfeld · Dänemark" },
  { name: "James Maddison", hint: "Mittelfeld · England" },
  { name: "Cole Palmer", hint: "Mittelfeld · England" },
  { name: "Aleksandar Pavlović", hint: "Mittelfeld · Deutschland" },
  { name: "Julian Brandt", hint: "Mittelfeld · Deutschland" },
  { name: "Arda Güler", hint: "Mittelfeld · Türkei" },
  { name: "Xavi Simons", hint: "Mittelfeld · Niederlande" },
  { name: "Lamine Yamal", hint: "Flügel · Spanien" },
  { name: "Nico Williams", hint: "Flügel · Spanien" },
  { name: "Raphinha", hint: "Flügel · Brasilien" },
  { name: "Ferran Torres", hint: "Stürmer · Spanien" },
  { name: "Rodrygo", hint: "Flügel · Brasilien" },
  { name: "Endrick", hint: "Stürmer · Brasilien" },
  { name: "Julián Álvarez", hint: "Stürmer · Argentinien" },
  { name: "Mauro Icardi", hint: "Stürmer · Argentinien" },
  { name: "Alejandro Garnacho", hint: "Flügel · Argentinien" },
  { name: "Darwin Núñez", hint: "Stürmer · Uruguay" },
  { name: "Luis Díaz", hint: "Flügel · Kolumbien" },
  { name: "Jhon Durán", hint: "Stürmer · Kolumbien" },
  { name: "Matheus Cunha", hint: "Stürmer · Brasilien" },
  { name: "Pedro Neto", hint: "Flügel · Portugal" },
  { name: "Gonçalo Ramos", hint: "Stürmer · Portugal" },
  { name: "João Félix", hint: "Stürmer · Portugal" },
  { name: "Michael Olise", hint: "Flügel · Frankreich" },
  { name: "Bradley Barcola", hint: "Flügel · Frankreich" },
  { name: "Randal Kolo Muani", hint: "Stürmer · Frankreich" },
  { name: "Christopher Nkunku", hint: "Stürmer · Frankreich" },
  { name: "Hugo Ekitike", hint: "Stürmer · Frankreich" },
  { name: "Rasmus Højlund", hint: "Stürmer · Dänemark" },
  { name: "Viktor Gyökeres", hint: "Stürmer · Schweden" },
  { name: "Benjamin Šeško", hint: "Stürmer · Slowenien" },
  { name: "Serhou Guirassy", hint: "Stürmer · Guinea" },
  { name: "Victor Boniface", hint: "Stürmer · Nigeria" },
  { name: "Ademola Lookman", hint: "Flügel · Nigeria" },
  { name: "Omar Marmoush", hint: "Stürmer · Ägypten" },
  { name: "Youssef En-Nesyri", hint: "Stürmer · Marokko" },
  { name: "Brahim Díaz", hint: "Mittelfeld · Marokko" },
  { name: "Nicolas Jackson", hint: "Stürmer · Senegal" },
  { name: "Karim Adeyemi", hint: "Flügel · Deutschland" },
  { name: "Deniz Undav", hint: "Stürmer · Deutschland" },
  { name: "Nick Woltemade", hint: "Stürmer · Deutschland" },
  { name: "Kenan Yıldız", hint: "Stürmer · Türkei" },
  { name: "Antonio Nusa", hint: "Flügel · Norwegen" },
  { name: "Giovanni Reyna", hint: "Mittelfeld · USA" },
  { name: "Andrej Kramarić", hint: "Stürmer · Kroatien" },

  // --- Weitere bekannte Spieler ---
  { name: "David de Gea", hint: "Torwart · Spanien" },
  { name: "Jan Oblak", hint: "Torwart · Slowenien" },
  { name: "Hugo Lloris", hint: "Torwart · Frankreich" },
  { name: "Wojciech Szczęsny", hint: "Torwart · Polen" },
  { name: "Yann Sommer", hint: "Torwart · Schweiz" },
  { name: "Keylor Navas", hint: "Torwart · Costa Rica" },
  { name: "Kasper Schmeichel", hint: "Torwart · Dänemark" },
  { name: "Harry Maguire", hint: "Verteidiger · England" },
  { name: "Luke Shaw", hint: "Verteidiger · England" },
  { name: "Andrew Robertson", hint: "Verteidiger · Schottland" },
  { name: "Jordi Alba", hint: "Verteidiger · Spanien" },
  { name: "Aymeric Laporte", hint: "Verteidiger · Spanien" },
  { name: "Kalidou Koulibaly", hint: "Verteidiger · Senegal" },
  { name: "Nicolás Otamendi", hint: "Verteidiger · Argentinien" },
  { name: "Sergio Busquets", hint: "Mittelfeld · Spanien" },
  { name: "Isco", hint: "Mittelfeld · Spanien" },
  { name: "Jorginho", hint: "Mittelfeld · Italien" },
  { name: "Marco Verratti", hint: "Mittelfeld · Italien" },
  { name: "Adrien Rabiot", hint: "Mittelfeld · Frankreich" },
  { name: "Rodrigo De Paul", hint: "Mittelfeld · Argentinien" },
  { name: "Georginio Wijnaldum", hint: "Mittelfeld · Niederlande" },
  { name: "Ivan Rakitić", hint: "Mittelfeld · Kroatien" },
  { name: "Marcelo Brozović", hint: "Mittelfeld · Kroatien" },
  { name: "Ivan Perišić", hint: "Flügel · Kroatien" },
  { name: "Leon Goretzka", hint: "Mittelfeld · Deutschland" },
  { name: "Emre Can", hint: "Mittelfeld · Deutschland" },
  { name: "Mario Götze", hint: "Mittelfeld · Deutschland" },
  { name: "Mason Mount", hint: "Mittelfeld · England" },
  { name: "Jordan Henderson", hint: "Mittelfeld · England" },
  { name: "Fabinho", hint: "Mittelfeld · Brasilien" },
  { name: "Philippe Coutinho", hint: "Mittelfeld · Brasilien" },
  { name: "Arturo Vidal", hint: "Mittelfeld · Chile" },
  { name: "Raheem Sterling", hint: "Flügel · England" },
  { name: "Jadon Sancho", hint: "Flügel · England" },
  { name: "Anthony Martial", hint: "Stürmer · Frankreich" },
  { name: "Pierre-Emerick Aubameyang", hint: "Stürmer · Gabun" },
  { name: "Wilfried Zaha", hint: "Flügel · Elfenbeinküste" },
  { name: "Alexis Sánchez", hint: "Stürmer · Chile" },
  { name: "Edinson Cavani", hint: "Stürmer · Uruguay" },
  { name: "Paulo Dybala", hint: "Stürmer · Argentinien" },
  { name: "Álvaro Morata", hint: "Stürmer · Spanien" },
  { name: "Marco Asensio", hint: "Flügel · Spanien" },
  { name: "Ciro Immobile", hint: "Stürmer · Italien" },
  { name: "Lorenzo Insigne", hint: "Flügel · Italien" },
  { name: "Hakim Ziyech", hint: "Flügel · Marokko" },
  { name: "Timo Werner", hint: "Stürmer · Deutschland" },
  { name: "Niclas Füllkrug", hint: "Stürmer · Deutschland" },
  { name: "Gabriel Jesus", hint: "Stürmer · Brasilien" },
  { name: "Richarlison", hint: "Stürmer · Brasilien" },
  { name: "Roberto Firmino", hint: "Stürmer · Brasilien" },
  { name: "Antony", hint: "Flügel · Brasilien" },
  { name: "Gabriel Martinelli", hint: "Flügel · Brasilien" },
  { name: "Wout Weghorst", hint: "Stürmer · Niederlande" },
  { name: "Sébastien Haller", hint: "Stürmer · Elfenbeinküste" },
  { name: "Franck Ribéry", hint: "Flügel · Frankreich" },
  { name: "Raphaël Varane", hint: "Verteidiger · Frankreich" },
  { name: "Giorgio Chiellini", hint: "Verteidiger · Italien" },
  { name: "Leonardo Bonucci", hint: "Verteidiger · Italien" },
  { name: "Thiago Alcântara", hint: "Mittelfeld · Spanien" },
  { name: "Pepe", hint: "Verteidiger · Portugal" },
  { name: "Rio Ferdinand", hint: "Verteidiger · England" },
  { name: "John Terry", hint: "Verteidiger · England" },
  { name: "Ashley Cole", hint: "Verteidiger · England" },
  { name: "Michael Owen", hint: "Stürmer · England" },
  { name: "Paul Scholes", hint: "Mittelfeld · England" },
  { name: "Ryan Giggs", hint: "Flügel · Wales" },
  { name: "Patrick Vieira", hint: "Mittelfeld · Frankreich" },
  { name: "Alessandro Nesta", hint: "Verteidiger · Italien" },
  { name: "Diego Godín", hint: "Verteidiger · Uruguay" }
].filter(function (p) { return p.name && p.hint; });
